### ISSUE TITLE
Why does this command line always break a long string into multiple lines?

### ISSUE THREAD

**Issue by kernelogic** [smarty-gettext/tsmarty2c#17]
For example in my tpl file it looks like this in one line. Can I disable this feature?

```
{t escape=no}Thank you for visiting, please <a href="/index.php?page=logon&event=">click here</a> to return to the login screen, if your browser does not automatically take you there.{/t}
```

but after prcoessing it becomes this:

```po
#: html_templates/smarty//logout_body.tpl:7 
msgid ""
 "Thank you for visiting, please <a href=\"/index.php?page=logon&event=" 
"\">click here</a> to return to the login screen, if your browser does not "
 "automatically take you there." 
msgstr ""
```

**Comment by glensc** [comment]
That's an identical string, using line wrapping by .po file syntax. pay extra attention to the quotes.

if you don't like that, you can always reformat the file with larger width:

```
msgcat --width=2000 < input.po > output.po

```

doc:
- https://www.gnu.org/software/gettext/manual/html_node/msgcat-Invocation.html


you should not edit the .po/.pot files manually, so it should not be an issue at all.

**Comment by glensc** [comment]
also, you should not include url in your translations, use %1 placeholders instead:

```smarty
{t escape=no 1="/index.php?page=logon&event="}Thank you for visiting, please <a href="%1">click here</a> to return to the login screen, if your browser does not automatically take you there.{/t}
```
