### ISSUE TITLE
tsmarty2c.php -V report incorrect version

### ISSUE THREAD

**Issue by kumy** [smarty-gettext/tsmarty2c#23]
The wrong version is displayed:

```
$ ./vendor/bin/tsmarty2c.php -V
Smarty Gettext Translation String Ripper 0.1.0
```

While v0.2.1 is installed
```
$ php composer.phar show smarty-gettext/tsmarty2c
name     : smarty-gettext/tsmarty2c
descrip. : Smarty Gettext Translation String Ripper
keywords : 
versions : * 0.2.1
type     : library

```

**Comment by glensc** [comment]
Pull requests are welcome!

**Comment by kumy** [comment]
How do you wish to handle that? I can manually update the version in the file, but have to increment the version as it will be included in a new release. but it will be a pain to maintain, no? Having it dynamic based on release process would be more efficient, but if the release is automatic, then it will need some commit push back to the repo.

**Comment by glensc** [comment]
There's no release automation, so just update the value and I can push the next version out.
